[package]
name = "qiskit-qobj-explorer"
version = "0.1.0"
authors = ["Juan Gomez <atilag@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
yew = "0.6"
stdweb = "0.4"
